name: regina_pratas_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  asuka: ^2.0.1
  dio: ^4.0.6
  firebase_analytics: ^9.3.3
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  firebase_remote_config: ^2.0.16
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^4.4.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.1
  logger: ^1.1.0
  mask_text_input_formatter: ^2.4.0
  path: ^1.8.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1
  synchronized: ^3.0.0+2
  validatorless: ^1.2.1

dev_dependencies:
  dart_code_metrics: ^4.17.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    #   - assets/images/
    - .env
