name: regina_pratas_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  asuka: ^2.0.0+1
  dio: ^4.0.6
  firebase_analytics: ^9.3.0
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  firebase_remote_config: ^2.0.13
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^4.4.0+1
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.3
  flutter_native_splash: ^2.2.7
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^5.1.0
  google_sign_in: ^5.4.0
  logger: ^1.1.0
  mobx: ^2.0.7+5
  shared_preferences: ^2.0.15
  validatorless: ^1.2.1

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.17.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
