name: regina_pratas_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  asuka: ^2.0.1+3
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  firebase_remote_config: ^2.0.20
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^4.4.1+1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  flutter_modular: ^5.0.3
  flutter_native_splash: ^2.2.10+1
  flutter_screenutil: ^5.5.4
  flutter_secure_storage: ^6.0.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  logger: ^1.1.0
  mask_text_input_formatter: ^2.4.0
  mobx: ^2.1.1
  path: ^1.8.2
  shared_preferences: ^2.0.15
  sqflite: ^2.1.0+1
  synchronized: ^3.0.0+3
  validatorless: ^1.2.3

dev_dependencies:
  build_runner: ^2.3.0
  dart_code_metrics: ^4.19.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7+3

flutter:
  uses-material-design: true

  assets:
    #   - assets/images/
    - .env
